----------------
--- MONITORS ---
----------------

hl.config({ autogenerated = false })

hl.monitor({
  output = "eDP-1",
  mode = "preferred",
  position = "auto",
  scale = "1",
  transform = 0,
})

hl.monitor({
  output = "SUNSHINE",
  -- Fallback before Sunshine applies the Moonlight client's mode.
  mode = "1920x1080@60",
  position = "0x0",
  scale = "1",
})

-----------------------------
--- ENVIRONMENT VARIABLES ---
-----------------------------

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

---------------------
--- LOOK AND FEEL ---
---------------------

hl.config({
  general = {
    gaps_in = 2,
    gaps_out = 5,
    border_size = 2,
    col = {
      active_border = "rgba(ffffffff)",
      inactive_border = "rgba(111111ff)",
    },
    resize_on_border = true,
    allow_tearing = false,
    layout = "dwindle",
  },

  decoration = {
    rounding = 10,
    shadow = {
      enabled = false,
      range = 10,
      render_power = 4,
      color = "rgba(ffffffff)",
    },
    blur = {
      enabled = true,
      size = 3,
      passes = 1,
      vibrancy = 0.1696,
    },
  },

  animations = {
    enabled = true,
  },

  dwindle = {
    preserve_split = true,
  },

  master = {
    new_status = "master",
  },

  misc = {
    force_default_wallpaper = 1,
    disable_hyprland_logo = true,
    vrr = 0,
  },

  xwayland = {
    enabled = true,
    force_zero_scaling = true,
  },
})

hl.curve("wind", {
  type = "bezier",
  points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.curve("winIn", {
  type = "bezier",
  points = { { 0.1, 1.1 }, { 0.1, 1.1 } },
})
hl.curve("winOut", {
  type = "bezier",
  points = { { 0.3, -0.3 }, { 0, 1 } },
})
hl.curve("liner", {
  type = "bezier",
  points = { { 1, 1 }, { 1, 1 } },
})

hl.animation({ leaf = "windows", enabled = true, speed = 6, bezier = "wind", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 5, bezier = "winIn", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "winOut", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5, bezier = "wind", style = "slide" })
hl.animation({ leaf = "layers", enabled = true, speed = 1, bezier = "wind", style = "slide" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 5, bezier = "winIn", style = "slide" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1, bezier = "winOut", style = "slide" })
hl.animation({ leaf = "border", enabled = true, speed = 1, bezier = "liner" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 30, bezier = "liner", style = "loop" })
hl.animation({ leaf = "fade", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "wind", style = "slide" })

------------------------------
--- WINDOWS AND WORKSPACES ---
------------------------------

hl.window_rule({
  name = "suppress-maximize-events",
  match = { class = ".*" },
  suppress_event = "maximize",
})

hl.window_rule({
  name = "fix-xwayland-drags",
  match = {
    class = "^$",
    title = "^$",
    xwayland = true,
    float = true,
    fullscreen = false,
    pin = false,
  },
  no_focus = true,
})
