[[manager.prepend_keymap]]
on   = [ "g", "h" ]
run  = "cd ~/.config/hypr"
desc = "hypr folder"

[[manager.prepend_keymap]]
on   = [ "g", "1" ]
run  = "cd ~/.config/HybridBar/"
desc = "HybridBar folder"

[[manager.prepend_keymap]]
on   = [ "g", "~" ]
run  = "cd ~"
desc = "home folder"

[[manager.prepend_keymap]]
on   = [ "g", "2" ]
run  = "cd ~/Documents/"
desc = "Documents folder"

[[manager.prepend_keymap]]
on   = [ "n", "n" ]
run  = "shell 'nix-shell' --confirm"
desc = "nix-shell"

[[manager.prepend_keymap]]
on   = [ "n", "s" ]
run  = "shell 'zsh' --confirm"
desc = "zsh"
