alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias c="clear"
alias n="nvim"
alias py="python3"
alias pm="sudo pacman --noconfirm"
alias yy="yay --noconfirm"
alias cmatrix="cmatrix -C white"
alias neofetch="c && neofetch && read"
alias hde="hyprctl dispatch exec"
alias nv="nvim"
alias du="du -sh"
alias ns="nix-shell"
