bindkey -s "^L" 'ls -la^M'
bindkey -s "^U" 'c^M'
bindkey -s "^Y" 'yazi^M'
bindkey -s "^B" 'btop^M'
bindkey -s "^E" 'nv ^M'
bindkey -s "^Z" 'fg^M'
bindkey -s "^N" 'neofetch^M'
bindkey -s "^D" 'df -h^M'
bindkey -s "^T" 'du .^M'
