{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    hyprlock
    wget
    unzip
    gcc
    rocmPackages_5.llvm.clang
    go
    cargo
    gnumake42
    #wl-clipboard-rs
    wl-clipboard-x11
    xclip
    fzf
    telegram-desktop
    brightnessctl
    playerctl
    zsh
    alacritty
    ghostty
    git
    hyprpaper
    tor-browser
    networkmanagerapplet
    neofetch
    grim
    slurp
    grimblast
    gfortran
    libreoffice-qt6-fresh
    protonplus
    bottles
    cmatrix
    pipes-rs
    qbittorrent
    qalculate-gtk
    fxlinuxprint
    cups
    hal-hardware-analyzer
    usbutils
    dmg2img
    p7zip
    nodejs
    nwg-dock-hyprland
    kdePackages.calligra
    onlyoffice-desktopeditors
    obs-studio
    wineWowPackages.waylandFull
    wpsoffice-cn
    github-desktop
  ];
}
