{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    hyprlock
    wget
    unzip
    #wl-clipboard-rs
    wl-clipboard-x11
    xclip
    fzf
    telegram-desktop
    brightnessctl
    playerctl
    zsh
    alacritty
    ghostty
    git
    hyprpaper
    tor-browser
    networkmanagerapplet
    neofetch
    grim
    slurp
    grimblast
    protonplus
    bottles
    cmatrix
    pipes-rs
    qbittorrent
    qalculate-gtk
    fxlinuxprint
    cups
    hal-hardware-analyzer
    usbutils
    p7zip
    nodejs
    nwg-dock-hyprland
    obs-studio
    wineWowPackages.waylandFull
    github-desktop
  ];
}
