{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    hyprlock
    wget
    unzip
    #wl-clipboard-rs
    wl-clipboard-x11
    xclip
    fzf
    brightnessctl
    playerctl
    zsh
    alacritty
    git
    hyprpaper
    tor-browser
    networkmanagerapplet
    neofetch
    grim
    slurp
    grimblast
    cmatrix
    pipes-rs
    qbittorrent
    qalculate-gtk
    fxlinuxprint
    cups
    hal-hardware-analyzer
    usbutils
    p7zip
    nodejs
    obs-studio
    wineWowPackages.waylandFull
    github-desktop

    vlc
    nautilus
    nvidia-drivers
    pkgs.pipewire
  ];
}
